name: QA SaaS Runner
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm init -y
      - run: npm install @playwright/test
      - run: npx playwright install --with-deps chromium
      
      - name: Record Start Time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      
      - run: npx playwright test tests/saas.spec.ts
        
      - name: Report Success
        if: success()
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))s
          curl -X POST -H "Content-Type: application/json" -d '{"repo":"tasmeerhaider/portfolio", "status":"passed", "executionTime":"'$DURATION'", "logUrl":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' https://till-unpledged-half.ngrok-free.dev/api/webhook

      - name: Report Failure
        if: failure()
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))s
          curl -X POST -H "Content-Type: application/json" -d '{"repo":"tasmeerhaider/portfolio", "status":"failed", "executionTime":"'$DURATION'", "logUrl":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' https://till-unpledged-half.ngrok-free.dev/api/webhook